---
title: "PCA plots"
output: html_notebook
---

```{r libraries, echo = FALSE}
library(tidyverse)
library(ggrepel)
library(fs)
library(RcppCNPy)
```


Checking for any lane, pool, or sequencer effects:
```{r data_org, echo = FALSE}
metadata <- read_csv("data/CCGP_squid-metadata.csv", 
                     show_col_types = FALSE) %>%
  select(PoolName, Sequencer, NMFS_DNA_ID...6, 
         GENUS, SPECIES, COLLECTION_DATE, 
         LANDFALL_PORT, CRUISE, HAUL, 
         SITE, STATE_M, LATITUDE_M, LONGITUDE_M)
### First 108 samples ###
C <- as.matrix(read.table("data/hc_pools/bcf_testy/thin_100_1/pcangsd/output.cov"))
NMFS_DNA_ID <- read_lines("data/hc_pools/bcf_testy/thin_100_1/samples.txt")
e <- eigen(C)
t <- tibble(PC1 = e$vectors[,1], 
            PC2 = e$vectors[,2], 
            PC3 = e$vectors[,3], 
            PC4 = e$vectors[,4])
temp <- add_column(t, NMFS_DNA_ID)
data <- left_join(temp, 
                  metadata, 
                  by = c("NMFS_DNA_ID" = "NMFS_DNA_ID...6"))

vars <- e$values/sum(e$values) * 100

```

```{r data_vis, echo = FALSE}
wn_colors <- c(`California` = "steelblue3", 
               `Alaska` = "thistle", 
               `Oregon` = "tomato3")
```

```{r hc_pools, echo = FALSE}
plot <- ggplot(data = data,
               mapping = aes(x = PC1,
                             y = PC2,
                             fill = as.character(LATITUDE_M))) +
  geom_point(size = 3, 
             shape = 24) + 
  geom_point(stroke = 0.05,
             alpha = 0.75,
             size = 3.5, 
             shape = 24) +
## scale_fill_manual(values = wn_colors) +
##  scale_shape_manual(values = sp_shapes) +
  theme_bw() +
  theme(panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(override.aes = list(shape = 22, 
                                                 stroke = 0.05, 
                                                 size = 3)), 
         shape = guide_legend(override.aes = list(stroke = 0.05, 
                                                  size = 3))) +
  labs(fill = "STATE_m", 
       x = paste0("PC1 (",round(vars[1], 2),"%)"),
       y = paste0("PC2 (",round(vars[2], 2),"%)")) +
  geom_text_repel(mapping = aes(label = HAUL), 
                  max.overlaps = 25)
plot
```


```{r}
### next 128 samples ###
C <- as.matrix(read.table("data/lc_pools/bcf_pools78/thin_100_1/pcangsd/lc-pools.iter10000.pcangsd.output.cov"))
NMFS_DNA_ID <- read_lines("data/lc_pools/bcf_pools78/thin_100_1/samples.txt")
e <- eigen(C)
t <- tibble(PC1 = e$vectors[,1], 
            PC2 = e$vectors[,2], 
            PC3 = e$vectors[,3], 
            PC4 = e$vectors[,4])
temp <- add_column(t, NMFS_DNA_ID)
data2 <- left_join(temp, 
                  metadata, 
                  by = c("NMFS_DNA_ID" = "NMFS_DNA_ID...6"))

vars2 <- e$values/sum(e$values) * 100

```

```{r lc_pools}
plot <- ggplot(data = data2,
               mapping = aes(x = PC1,
                             y = PC2,
                             fill = as.character(LATITUDE_M))) +
  geom_point(size = 3, 
             shape = 24) + 
  geom_point(stroke = 0.05,
             alpha = 0.75,
             size = 3.5, 
             shape = 24) +
## scale_fill_manual(values = wn_colors) +
##  scale_shape_manual(values = sp_shapes) +
  theme_bw() +
  theme(panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(override.aes = list(shape = 22, 
                                                 stroke = 0.05, 
                                                 size = 3)), 
         shape = guide_legend(override.aes = list(stroke = 0.05, 
                                                  size = 3))) +
  labs(fill = "State", 
       x = paste0("PC1 (",round(vars2[1], 2),"%)"),
       y = paste0("PC2 (",round(vars2[2], 2),"%)")) +
  geom_text_repel(mapping = aes(label = NMFS_DNA_ID), 
                  max.overlaps = 25)
plot
```


```{r}
### all samples simply bunged together with bcftools ###
C <- as.matrix(read.table("data/all_bunged/allCCGP_bunged.pcangsd.output.cov"))
NMFS_DNA_ID <- read_lines("data/all_bunged/samples.txt")
e <- eigen(C)
t <- tibble(PC1 = e$vectors[,1], 
            PC2 = e$vectors[,2], 
            PC3 = e$vectors[,3], 
            PC4 = e$vectors[,4])
temp <- add_column(t, NMFS_DNA_ID)
data3 <- left_join(temp, 
                  metadata, 
                  by = c("NMFS_DNA_ID" = "NMFS_DNA_ID...6"))

vars3 <- e$values/sum(e$values) * 100

```

```{r all_bunged}
plot <- ggplot(data = data3,
               mapping = aes(x = PC1,
                             y = PC2,
                             fill = as.character(PoolName))) +
  geom_point(size = 3, 
             shape = 24) + 
  geom_point(stroke = 0.05,
             alpha = 0.75,
             size = 3.5, 
             shape = 24) +
## scale_fill_manual(values = wn_colors) +
##  scale_shape_manual(values = sp_shapes) +
  theme_bw() +
  theme(panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(override.aes = list(shape = 22, 
                                                 stroke = 0.05, 
                                                 size = 3)), 
         shape = guide_legend(override.aes = list(stroke = 0.05, 
                                                  size = 3))) +
  labs(fill = "State", 
       x = paste0("PC1 (",round(vars3[1], 2),"%)"),
       y = paste0("PC2 (",round(vars3[2], 2),"%)")) +
  geom_text_repel(mapping = aes(label = NMFS_DNA_ID), 
                  max.overlaps = 25)
plot
```
